export const FECTH_GITHUB_PUBLIC_REPO = "FETCH_GITHUB_PUBLIC_REPO"
export const FETCH_OTHER_USER_DETAILS = "FETCH_OTHER_USER_DETAILS"
export const FETCH_GITHUB_AUTH_CALLBACK = "FETCH_GITHUB_AUTH_CALLBACK"
